title: ETB Projects
description: A Collaborative STEM Project.
theme: just-the-docs
url: https://etbprojects.com

favicon_ico: "/assets/image/favicon.ico"

aux_links:
  GitHub Repo: https://github.com/etbprojects/etbprojects.github.io

footer_content: >
  Â© 2025 ETB Projects | ğŸ  HQ: Ann Arbor, MI, USA | ğŸ“© Contact: <a href="mailto:yazuardi@umich.edu">yazuardi@umich.edu</a>
